post http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0YjUwM2IyNjYxMWI5ZTRlMDNhZTFjNiIsImlhdCI6MTY4OTU4ODA0Nn0.Y_4zVejLXaHU3MpySbwV9MGn_ApaopTzojynaKL7BDE

{
  "content": "rel note",
  "important": true
}